config/routes.rb
KleineRailsdoku::Application.routes.draw do
  
  root :to => 'pages#home'
  
  match '/kapitel3', :to => 'pages#kapitel3'
  match '/kapitel4', :to => 'pages#kapitel4'
  match '/kapitel5', :to => 'pages#kapitel5'
  match '/kapitel6', :to => 'pages#kapitel6'
  match '/cheatsheet', :to => 'pages#cheatsheet'
  match '/bericht', :to => 'pages#bericht'
  
  get "pages/home"

  get "pages/kapitel3"

  get "pages/kapitel4"

  get "pages/kapitel5"

  get "pages/kapitel6"

  get "pages/cheatsheet"

  get "pages/bericht"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		
	end

	def kapitel3
		@title = "Kapitel 3"
	end

	def kapitel4
		@title = "Kapitel 4"
	end

	def kapitel5
 		@title = "Kapitel 5"
	end

	def kapitel6
		@title = "Kapitel 6"
	end

	def cheatsheet
		@title = "Cheatsheet"
	end

	def bericht
		@title = "Bericht"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# Richtigen Titel für jede Seite zurück geben
	def title
		
		main_title = "Kleine Railsdoku"
		
		if (@title.nil?)
			return main_title
		else
			return @title + ' - ' + main_title
		end
		
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<p><a href="http://creativecommons.org/licenses/by-nc-sa/2.5/ch/">CC BY-NC-SA</a> 2011 by David Keller. Zusammenfassungen aus dem Buch <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> von <a href="http://michaelhartl.com/">Michael Hartl</a>.</p>
</footer>

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><span><%= link_to "Home", root_path %></span></li>
		<li><span><%= link_to "Kapitel 3", kapitel3_path %></span></li>
		<li><span><%= link_to "Kapitel 4", kapitel4_path %></span></li>
		<li><span><%= link_to "Kapitel 5", kapitel5_path %></span></li>
		<li><span><%= link_to "Kapitel 6", kapitel6_path %></span></li>
		<li><span><%= link_to "Cheatsheet", cheatsheet_path %></span></li>
		<li><span><%= link_to "Bericht", bericht_path %></span></li>
	</ul>			
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= stylesheet_link_tag 'style', :media => 'screen' %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		
		<div class="container">
			
			<header>
				<h1>Kleine Railsdoku</h1>
			</header>

			<%= render 'layouts/navigation' %>
			
			<section class="content">
				<%= yield %>
			</section>
			
			<%= render 'layouts/footer' %>
		
		</div>

	</body>
</html>

app/views/pages/bericht.html.erb
<h1>Bericht</h1>

<p>Zu Beginn meines Projekts war mein Ziel, eine Seite mit <em>Ruby on Rails</em> erstellen, welche dem Benutzer ein Anmeldeformular anzeigt. Diese Daten sollten dann in einer Datenbank gespeichert werden und vom Administrator nach einer Autentifizierung eingesehen und bearbeitet werden. Damit könnte zum Beispiel eine Anmeldung für ein Konzert verwirklicht werden.</p>

<p>Ich stellte aber fest, dass ich etwas Richtiges in <em>Ruby on Rails</em> schreiben wollte, das solide ist und ich auch weiter verwenden kann. Ruby konnte ich schon, aber von <em>Ruby on Rails</em> hat ich noch nicht viel Ahnung. Darum beschloss ich im Rahmen meines Projekts <em>Ruby on Rails</em> zu lernen.</p>

<p>Zuerst arbeitete ich das interaktive <a href="http://railsforzombies.org/"><em>Rails for Zombies</em></a>-Tutorial druch. Dort konnte ich viele Teile von <em>Rails</em> mal erfahren, aber so wirklich eine gute Grundlange hat es mir nicht geboten.</p>

<p>So bin ich auf das Onlinebuch <a href="http://railstutorial.org/"><em>Ruby on Rails Tutorial: Learn Rails by Example</em></a> von <a href="http://michaelhartl.com/">Michael Hartl</a> gestossen. Dieses arbeite ich aktuell druch und es bringt einem <em>Rails</em> Stück für Stück näher. Damit ich die Essesz dieses Buches auch immer wieder griffbereit habe, habe ich angefangen die Kapitel zusammenzufassen. Da die ersten zwei Kapitel nur ein bisschen <em>Rails</em> zeigen, aber nocht nicht wirklich relevanten Inhalt bieten beginnt meine Zusammenfassung erst mit dem dritten Kapitel. Momentan bin ich bis zu sechsten Kapitel gekommen (was auch mein Ziel für das Projekt war). Ich habe aber noch vor, weiter zu lesen und dann die Kapitel auch als Zusammenfassung auf dieser Seite zu veröffentlichen.</p>

<p>Damit die Praxis, welche eigentlich vom Projekt vor allem gefordert wurde, nicht komplett gestrichen wurde, ist diese Seite hier komplett in <em>Rails</em> geschrieben. Damit konnte ich alles gelernte nochmals repetieren und meine erste selbständige Railsapp schreiben.</p>

<p>Was ich sehr interessant gefunden habe am Railsbuch ist das Schreiben von Tests für eine Railsapp. Ich habe gemerkt, dass solche Tests, sofern sich richtig eingesetzt werden, sehr hilfreich sind. So können viele Bugs von Tests abgefangen werden.</p>

app/views/pages/cheatsheet.html.erb
<h1>Cheatsheet</h1>

<h2>Allgemein</h2>

<p>Testserver unter <a href="http://localhost:3000">localhost:3000</a> starten:</p>

<pre><code>$ rails server # oder $rails s
</code></pre>

<p>Railskonsole:</p>

<pre><code>$ rails console # oder $ rails c
</code></pre>

<p>Konsole, die nichts in der Datenbank speichert:</p>

<pre><code>$ rails c --sandbox
</code></pre>

<p>Alle Tests laufen lassen:</p>

<pre><code>$ rspec /spec
</code></pre>

<h2>Neue Railsinstanz mit RSpec als Testframework</h2>

<pre><code>$ rails new programmname -T
</code></pre>

<p>Im Gemfile (<code>programmname/Gemfile</code>) folgende Zeilen einfügen:</p>

<pre><code>group :development do
  gem 'rspec-rails'
end

group :test do
  gem 'rspec'
  gem 'webrat'
end
</code></pre>

<p>Die Gems installieren:</p>

<pre><code>$ bundle install
</code></pre>

<p>RSpec installieren:</p>

<pre><code>$ rails generate rspec:install
</code></pre>

<h2>Rails generate</h2>

<h3>Neuer Controller</h3>

<pre><code>$ rails generate controller Controllername methodenname1 [methodenname2 ...] 
    # Es können beliebig viele Methodennamen hinzugefügt werden
</code></pre>

<h3>Neues Model</h3>

<pre><code>$ rails generate model Modelname parameter1:typ1 [parameter2:typ2 ...]
</code></pre>

<p>Die Datenbank auf den aktuellen Stand migrieren:</p>

<pre><code>$ rake db:migrate
</code></pre>

<p>Die Testdatenbank auch auf den aktuellen Stand bringen:</p>

<pre><code>$ rake db:test:prepare
</code></pre>

<p>Die Datenbank zurück migriegen:</p>

<pre><code>$ rake db:rollback
</code></pre>

<h3>Neuer Integrationstest</h3>

<pre><code>$ rails generate integration_test name_des_tests
</code></pre>

<h2>Gitrepository & Deployement nach Heroku</h2>

<pre><code>$ git init   # Gitrepositroy anlegen
$ git add .  # Alle Dateien in das Repository aufnehmen
$ git commit -m "Initialer Commit"

# Optional GitHub hinzufügen (nachem das neue Repository auf GitHub angelegt wurde)
$ git remote add origin git@github.com:&lt;Benutzername&gt;/programmname.git
$ git push origin master  # Nachher sollte $ git push reichen

$ heroku create NamederSubdomain
$ git push heroku master # Nachher sollte $ git push heroku reichen
$ heroku open # Die Instanz im Browser öffnen
</code></pre>

app/views/pages/home.html.erb
<h1>Home</h1>

<p>Im Rahmen von Projekten im Ergänzungsfach Informatik habe ich <a href="http://rubyonrails.org/">Ruby on Rails</a> mit Hilfe des Onlinebuches <a href="http://railstutorial.org/"><em>Ruby on Rails Tutorial: Learn Rails by Example</em></a> von <a href="http://michaelhartl.com/">Michael Hartl</a> gelernt. Um die Essenz der Kapitel 3 bis 5 immer griffbereit zu haben, habe ich diese zusammengefasst. Diese können über die Navigation eingesehen werden. Weiter habe ich ein Cheatsheet mit allen wichtigen Befehlen erstellt und einen Bericht zu meiner Arbeit geschrieben.</p>

<p>Diese Seite ist auch eine Railsapp und der Quelltext davon kann bei <a href="https://github.com/fossil12/Kleine-Railsdoku">Github</a> eingesehen und heruntergeladen werden. Wie dass dann die App lokal gestartet werden kann, steht dort.</p>

app/views/pages/kapitel3.html.erb
<h1>Kapitel 3</h1>

<h2>Erstellen einer neuen Railsinstanz</h2>

<p>Alle nötigen Befehle für das Erstellen und Einrichten einer Railsapp mit <a href="http://rspec.info/">RSpec</a> als Testframework.</p>

<p>Neue Railsinstannz im Ordner <code>programmname</code> ohne Standardtests (<code>-T</code>):</p>

<pre><code>$ rails new programmname -T
</code></pre>

<p>Damit nun respec als Testframework läuft, müssen folgende Zeilen zum Gemfile (<code>programmname/Gemfile</code>) hizugefügt werden:</p>

<pre><code>group :development do
  gem 'rspec-rails'
end

group :test do
  gem 'rspec'
  gem 'webrat'
end
</code></pre>

<p>Um die gems zu installieren wir nun:</p>

<pre><code>$ bundle install
</code></pre>

<p>aufgerufen. Und rspec muss dann auch installiert werden:</p>

<pre><code>$ rails generate rspec:install
</code></pre>

<p>Zuletzt noch ein git-Reporitory erstellen, um eine Versionierung zu haben und diese zum Beispiel bei <a href="http://github.com">GitHub</a> zu backupen. </p>

<pre><code>$ git init
$ git add .  # Alle Dateien in das Repository aufnehmen
$ git commit -m "Initialer Commit"

# Optional GitHub hinzufügen (nachem das neue Repository auf GitHub angelegt wurde)
$ git remote add origin git@github.com:&lt;Benutzername&gt;/programmname.git
$ git push origin master  # Nachher sollte $ git push reichen
</code></pre>

<p>Mit dem Erstellen eines git-Repositorys kann dann die Railsinstanz, auch ganz einfach zu <a href="http://heroku.com">Heroku</a> gepusht werden, wo sie produktiv verwendet werden kann.</p>

<pre><code>$ heroku create # Jenachdem heroku noch installieren mit $ gem install heroku
$ git push heroku master # Nachher sollte $ git push heroku reichen
$ heroku open # Die Instanz im Browser öffnen
</code></pre>

<h2>Statische Seiten</h2>

<p>Alle rein statischen Seiten, die in <code>programmname/public</code> liegen, werden von Rails direkt so ausgeliefert.</p>

<p>Statische Seiten im Sinne von Rails sind Seiten, die von einem Controller (Rails setzt auf die <a href="http://de.wikipedia.org/wiki/Model_View_Controller">Model View Controller-Architektur</a> (MVC)) ausgeliefert werden, aber keine dynamischen Daten aus einer Datenbank laden.</p>

<h3>Conroller mit Rails generieren</h3>

<p>Um einen Controller und Views für solche statischen Seiten zu erzeugen kann folgender Befehl genutzt werden:</p>

<pre><code>$ rails generate controller Controllername methodenname1 [methodenname2 ...] 
	# Es können beliebig viele Methodennamen hinzugefügt werden
</code></pre>

<p>Dabei wird in <code>programmanme/app/controllers</code> ein neuer Controller mit dem vorgegebenen Namen und <code>Controller</code> dahinter angelegt, in <code>programmname/app/views/conrollername</code> wir ein View für jede Methode angelegt und in <code>programmname/spec</code> werden Dateien für die Tests angelegt, von denen nur diejenigen in <code>controller</code> gebraucht werden. Der Rest kann getrost gelöscht werden. Schlussendlich werden in <code>programmname/config/routes.rb</code> die URLs für die Seiten (welche den Views und Methoden ensprechen) definiert, damit sie auf gerufen werden können.</p>

<h3>Rails mit lokalem Server testen</h3>

<p>Mit</p>

<pre><code>$ rails server # oder kurz $ rails s
</code></pre>

<p>kann ein lokaler Server gestartet werden und unter <code>http://localhost:3000</code> Startseite aufgerufen werden. Die gerade erzeugten Views können über die angegebenen Pfade in <code>routes.rb</code> angesurft werden (z. B. <code>http://loclahost:3000/controllername/methodenname1</code>).</p>

<h2>Test-driven developement (TDD)</h2>

<p>Test-driven developement bedeutet "testgetriebenes Entwickeln", das heisst, dass zuerst Tests geschrieben werden und danach die Funktion programmiert wird. Damit scheitern die Tests gezwungenermassen zuerst. Was als <em>rot</em> bezeichent wird. Wenn die Funktion implementiert wird, sollten die Tests erfolgreich durchgeführt werden - <em>grün</em>. Der letzte Schritt heisst <em>Überarbeiten</em>. Da die Tests vorhanden sind kann die Funktion auch nachträglich effizenter nochmals implementiert werden und sollte immer noch das gleiche tun solange es die Tests besteht.</p>

<p>Dadurch, dass die Tests zuerst geschrieben werden, wird auch sichergestellt, dass sie das testen, was sie testen sollen, denn sonst würde die implementierete Funktion sie nicht erfolgreich passieren.</p>

<p>Ein einfach Test kann so aussehen:</p>

<pre><code>describe "GET 'home'" do
  it "should be sucessful" do
    get 'home'
    response.should be_success
  end
end
</code></pre>

<p>Dabei ist das ganze auch Ruby, womit alle dessen Funktionen genutzt werden können. Die Linien, welche mit <code>describe</code> und <code>it</code> beginnen sind vor allem beschreibend und sollen in "normalem" Englisch erklären, was der Test testet. <code>describe</code> fasst dabei mehrere Tests zusammen und <code>it</code> beschreibt einen einzelnen Test. Mit <code>get</code> wird eine HTTP GET-Anfrage an die Methode <code>home</code> gesendet und mit <code>response.should be_success</code> getestet, ob die Seite (View zum Controller) vorhanden ist.</p>

<p>Um die Tests durzuführen wird folgendes Kommando eingegeben:</p>

<pre><code>$ rspec spec/
</code></pre>

<h2>Embedded Ruby</h2>

<p>Die Views von Rails werden in <em>embbedded Ruby</em> geschrieben. Grunsätzlich ist es normales HTML in das einfach Rubycode eingefügt wird und zwar wie folgt:</p>

<pre><code>&lt;% Code %&gt;
</code></pre>

<p>Diese Zeile wird dann in Ruby ausgeführt. Falls das Ergebniss ausgegeben werden soll, muss beim Öffnen ein <code>=</code> eingefügt werden. Das sieht dann folgendermassen aus.</p>

<pre><code>&lt;%= @titel %&gt;
</code></pre>

<p>Damit nicht für jeden View das ganze HTML-Grundgerüst geschrieben werden muss, das sowieso immer gleich ist, kann in <code>programmname/app/views/layouts/application.html.erb</code> ein Grundlayout angelegt werden. Mit <code>&lt;%= yield %&gt;</code> wird dann markiert, wo die Views eingefügt werden.</p>

<h3>Helper</h3>

<p>(Eigendlich in Kaptiel 4 erwähnt)</p>

<p>Mit Helpern (Helfern) können Funktionen definiert werden die direkt zum Layout gehören, aber nicht statisch in das Grundlayout geschrieben werden können. Helper für das Grundlayout können in <code>programmname/app/helpers/application_helper.rb</code> definiert werden. Ein Helper könnte beispielsweise der Title in der Menübar des Browsers sein. Die Basis ist immer gleich, aber der Titel der einzelnen Seiten kommt dann noch dyanamisch dazu.</p>

app/views/pages/kapitel4.html.erb
<h1>Kapitel 4 - Ruby</h1>

<p>Für Ruby gibt es die Testkonsole <code>irb</code>. In Rails gibt es das gleiche zusätzlich mit allen Rails-Funktionen und den selbst definierten in der App und zwar mit:</p>

<pre><code>$ rails console # oder kurz $ rails c
</code></pre>

<p>Um Datenbanken nicht nachwirkend zu verändern, kann die Konsole auch in einer Sandbox gestartet werden.</p>

<pre><code>$ rails c --sandbox
</code></pre>

<h2>Ruby Allgemein</h2>

<ul>
<li>Methoden, die am Ende ein Fragezeichen haben, geben immer ein Boolean zurück. Also richtig oder falsch.</li>
<li>Alles ist ein Objekt in Ruby.</li>
<li><code>nil</code> ist das einzige Objekt, das als Boolean <code>false</code> zurück gibt.</li>
</ul>

<h3>Definition von Methoden</h3>

<p>Definitionen in Ruby beginnen mit einem <code>def</code> und falls kein <code>return</code> explizit geschrieben wird, wird automatisch das zuletzt evaluartierte Resulatat zurück gegeben.</p>

<p>So sieht eine Funktion aus, die immer <code>"Hello World"</code> zurückgibt:</p>

<pre><code>def hello_world
    "Hello World"
end
</code></pre>

<h3>Definition von Klassen</h3>

<p>In Ruby ist, wie schon gesagt, alles ein Objekt. Es stammt also alles von einer Klasse ab. Diese Abstammung kann in jeder Klasse mit <code>.class</code> ausgelsesen werden.</p>

<p>Eine Klasse wird wie folgt definiert:</p>

<pre><code>class Word &lt; String
    # Methoden
end
</code></pre>

<p>Die Klasse heisst dann <code>Word</code> und erbt alle Funktionen von <code>String</code>.</p>

<p>Es können aber auch bestehende Klassen mit neuen Methoden erweitert werden, ohne selbst eine neue Klasse zu definieren.</p>

<p>Um Strings einen neue Methode beizubringen ist folgender Code nötig:</p>

<pre><code>class String
    def neueMethode
        # Methode
    end
end
</code></pre>

<p>Die Methode <code>initialize</code> in einer Klasse wird automatisch aufgerufen, wenn eine neuen Instanz mit <code>Klassenname.new</code> erzeugt wird.</p>

<h2>Strings</h2>

<ul>
<li><p>Können durch <code>""</code> erstellt werden.</p>

<p>z.B. <code>"foobar"</code></p></li>
<li><p>Können addiert werden.</p>

<pre><code>"foo" + "bar"
=&gt; "foobar"
</code></pre></li>
<li><p>Es gibt zwei Arten mit Variablen Strings zu erstellen.</p>

<ol>
<li><code>variable1 + " " + variable2</code></li>
<li><code>"#{variable1} #{varibale2}"</code></li>
</ol></li>
<li><p>Strings mit nur einfachen Anführungszeichen verhalten sich grundsätzlich gleich. Es wird aber nichts im String interpretiert, das heisst, dass keine Zeichen escaped werden müssen.</p>

<p><code>'\n'</code> ist zum Beispiel das gleich wie <code>"\\n"</code>.</p></li>
</ul>

<h2>Arrays</h2>

<ul>
<li><p>Können durch <code>[]</code> erstellt werden. Dabei werden einzelne Elemente durch Kommas getrennt.</p>

<p>z.B. <code>["foo", "bar", "baz"]</code></p>

<p>Eine weitere Möglichkeit Arrays zu erzuegen ist folgende:</p>

<pre><code>%w[foo bar baz]
</code></pre></li>
<li><p>Mit <code>.sort</code> können sie sortiert werden</p></li>
<li><p>Mit <code>.reverse</code> kann die Reiehenfolge umgekert werden.</p></li>
<li><p>Mit <code>.shuffle</code> kann eine zufällige Reihenfolge erzeugt werden.</p></li>
<li><p>Um alle Elemente in einen String zusammen zu fassen, kann <code>.join</code> aufgerufen werden. Es kann in einer Klammer nach der Methode auch optional ein Trenner definiert werden.</p></li>
</ul>

<h2>Blöcke</h2>

<p>Blöcke sind Schlaufen, die auf Arrays (oder Bereiche/ranges) angewendet werden können. Dabei kann z.B. mit <code>.each</code> eine <code>for</code>-Schleif aus anderen Programmiersprachen einfacher aufgeschrieben werden.</p>

<p>Es gibt Zwei mögliche Notiationen</p>

<pre><code>array = [1, 2, 3, 4]

array.each { |i| puts i }

array.each do |i|
    puts i
end</code></pre>

<p>Wobei empfohlen wird die erste Variante für Einzeiler zu verwenden und die zweite Variante für mehrzeilige Blöcke. Zwischen den <code>|</code> wird die Laufvariable (oder die Laufvariablen) definiert.</p>

<h2>Hashes</h2>

<p>Hashes sind sogenante Key-Value Array. Das heisst, dass jedes Elemente über einen bestimmten Namen aufgerufen werden kann.</p>

<ul>
<li><p>Durch <code>{}</code> werden Hashes erstellt</p>

<p>z.B. <code>{ "name" =&gt; "David Keller", "email" =&gt; "dev@davidkeller.me" }</code></p></li>
<li><p>Damit nicht immer mühsam String als Keys verwendet werden müssen, gibt es sogenannte <em>Symbole</em> in Ruby. Diese beginnen immer mit einem Doppelpunkt. Das vorhherige Beispiel könnte dann so aussehen:</p>

<pre><code>{ :name =&gt; "David Keller", :email =&gt; "dev@davidkeller.me" }
</code></pre></li>
</ul>

app/views/pages/kapitel5.html.erb
<h1>Kapitel 5</h1>

<p>In diesem Kapitel geht es auch noch um CSS. Da dies für den Autor dieser Zusammenfassung aber irrelevant ist, wird es hier nicht weiter erwähnt.</p>

<h2>Vordefinierte Helper in Rails</h2>

<p>Es gibt eine Reihe von Helpern, die in Ruby schon vordefiniert sind. Einige davon werden nun hier aufgezählt.</p>

<ul>
<li><p><code>stylesheet_link_tag</code></p>

<p>Wird, wie der Name schon sagt, zum Einbinden von Stylesheets (CSS-Dateien) verwendet. Als erster Parameter wird der relative Pfad zum Stylesheet im Ordner <code>programmname/public/stylesheet</code> angegeben (.css ist optional) und als zweites der Mediatyp in Form eines Hashes.</p>

<pre><code>stylesheet_link_tag 'style', :media =&gt; 'screen'
</code></pre>

<p>Hier sehen wir auch, dass bei einem Funktionsaufruf in Ruby keine Klammern gesetzt werden müssen und falls als letzter Parameter ein Hash übergeben wird, dort auch keine geschweiften Klammern nötig sind. Der Aufruf könnte auch folgendermassen geschrieben werden:</p>

<pre><code>stylesheet_link_tag('style', { :media =&gt; 'screen' })
</code></pre></li>
<li><p><code>image_tag</code></p>

<p>Der <code>image_tag</code> wird zum Einbinden von Bildern verwendet. Dabei wird zuerst auch der realtive Pfad zu <code>programmname/public/images</code> angegeben, danach als Hash der <code>alt</code>-Tag und optional die Klasse(n).</p>

<pre><code>image_tag("logo.png", :alt =&gt; "Logo der Firma X", :class =&gt; "logo")
</code></pre></li>
<li><p><code>link_to</code></p>

<p>Erzeugt Links, die vor allem für interne Verlinkungen sehr praktisch sind, da dann immer automatisch die richtigen Links gesetzt werden. <code>link_to</code> wird zuerst der zu verlinkende Text über geben, dann der Link und schlussendlich optional noch eine Klasse.</p>

<pre><code>link_to "Home", "/", :class =&gt; "home_link"
</code></pre></li>
</ul>

<h2>Partials</h2>

<p>Partials ermöglichen das Aufteilen des Layouts in noch mehr Teile als nur in das Hauptlayout und die indivituellen Views. Dabei muss im View-Ordner (<code>programmname/app/views</code>) eine Datei mit einem <code>_</code> davor angelegt werden. Diese kann dann ins Hauptlayout mit</p>

<pre><code>&lt;% render 'partial' %&gt;
</code></pre>

<p>eingebunden werden. Hier wird zum Beispiel die Datei <code>_partial.html.erb</code> eingebunden.</p>

<h2>Integrationstests, Routen &amp; Interne Verlinkung</h2>

<h3>Integrationstest</h3>

<p>Integrationstests, sind Tests, die die Railsapp testen, als seien sie Benutzer die mit ihrem Browser auf die App zugreifen.</p>

<p>Die Datei dafür kann folgendermassen generiert werden:</p>

<pre><code>$ rails generate integration_test name_des_tests
</code></pre>

<p>Um dann beispielsweise zu testen, ob unter <code>/</code> eine Startseite mit dem Titel Home erscheint, sind folgende Zeilen Testcode nötig:</p>

<pre><code>it "should have a Home page at '/'" do
    get '/'
    response.should have_selector('title', :content =&gt; "Home")
end
</code></pre>

<h3>Routen</h3>

<p>Um nun die Seite Kontakt aus dem Controller <code>Seiten</code> unter <code>/kontakt</code> erreichbar zu machen müssen sogenannte Routen in <code>programmname/config/routes.rb</code> eingetragen werden. Für unser Beispiel wäre das</p>

<pre><code>match '/kontakt', :to =&gt; 'seiten#kontakt'
</code></pre>

<p>Für die Startseite unter <code>/</code> muss dann nicht</p>

<pre><code>match '/', :to =&gt; 'seiten#home'
</code></pre>

<p>eingetragen werden, sondern es kann einfach</p>

<pre><code>root :to =&gt; 'seiten#home'
</code></pre>

<p>in die <code>routes</code>-Datei eingetragen werden.</p>

<h3>Interne Verlinkung</h3>

<p>In den <code>link_to</code>-Tag müssen dank der Routen nicht mehr explixit die Links angegeben werden, sondern sie können folgendermassen integriert werden:</p>

<pre><code>link_to "Home", root_path

link_to "Kontakt", kontakt_path
</code></pre>